### ISSUE TITLE
Logical Entity Name is not a required attribute for Request or Response Parameters

### ISSUE THREAD

**Issue by Power-Maverick** [drivardxrm/XTB.CustomApiManager#10]
Can you add a feature request that would allow for not selecting a logical name as it is not required for Request or Response Parameter? 
This will enable us to use "expando" entity instead.

---
- Deployment: Online
- DB Version: 9.2.21101.144
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.9.52
- Tool Version: 1.2021.10.57

**Comment by drivardxrm** [comment]
Hi @Power-Maverick,
Are you talking about the bound entity logical name at the creation of an API ?

Using the OOB editor, it seems that the value is needed when you choose Entity or Entity Collection 
![image](https://user-images.githubusercontent.com/38399134/141825994-e14f2df6-1933-4c19-9543-c822cb8e85c9.png)

I have tried to put 'expando' as the logical name and it errors out.
![image](https://user-images.githubusercontent.com/38399134/141826744-9ff24811-5425-49f2-89e5-e96e3a41a40b.png)

Do you have an example of what you are trying to achieve?

**Comment by Power-Maverick** [comment]
More information: [here](https://powermaverick.dev/2021/11/17/dataverse-custom-api-that-supports-json-schema/)

**Comment by drivardxrm** [comment]
Hi, @Power-Maverick Awesome post 🌟 , can't wait to try this
 
I will make the change ASAP

**Comment by drivardxrm** [comment]
@Power-Maverick, check the latest release v1.2021.11.59, the expando feature is implemented.
