### ISSUE TITLE
Support for OnPrem?

### ISSUE THREAD

**Issue by janis-veinbergs** [drivardxrm/XTB.CustomApiManager#17]
Looks like OnPrem v9.1 doesn't support `WorkflowSdkStepEnabled` and when opening the tool or trying to create new API, I get an error:
```
Error occured: 'customapi' entity doesn't contain attribute with Name = 'workflowsdkstepenabled' and NameMapping='Logical'.
```

I did check EntityDefinitions, and `workflowsdkstepenabled` is only available for `sdkmessagefilter` and `sdkmessage`.

Could you handle this case gracefully? Thanks.

**Comment by drivardxrm** [comment]
Hi @janis-veinbergs,
Thanks for your feedback.
I will include a fix in the next release.

**Comment by drivardxrm** [comment]
Hi @janis-veinbergs,

I think I have it fixed.
Since I don't have access to an on-prem instance, would you mind testing the new version before I publish it?

[XTB.CustomApiManager.1.2023.2.92.zip](https://github.com/drivardxrm/XTB.CustomApiManager/files/10670983/XTB.CustomApiManager.1.2023.2.92.zip)

**Comment by janis-veinbergs** [comment]
Thanks. Seems I have the same error
![workflowsdkstepenabled error](https://i.imgur.com/02j6h1G.png)

1. Opened the tool
2. Pressed Create New API
3. Filled in details, except for plugintype (bindingtype entity = account)

However in UI i don't see that checkbox for enabling/disabling workflow feature.

**Comment by drivardxrm** [comment]
Half way there ;)
I'll send you another version shortly.

Thanks

**Comment by drivardxrm** [comment]
Hi @janis-veinbergs 
Can you try it out with this one.
[XTB.CustomApiManager.1.2023.2.93.zip](https://github.com/drivardxrm/XTB.CustomApiManager/files/10691376/XTB.CustomApiManager.1.2023.2.93.zip)

**Comment by janis-veinbergs** [comment]
Hey it works! Thank you very much. Request/Response params works too.

However Custom API tester won't work, but it is not your issue :) The crazy thing is that [CustomAPIRequestParameter](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/customapirequestparameter?view=dataverse-latest) for

**Comment by janis-veinbergs** [comment]
Hi, this works, thanks! Edit/Delete works; Created request/response params too.

**Comment by janis-veinbergs** [comment]
By the way, there is issue opening it in Custom API Tester, I filed it under appropriate repo as this is not your issue: https://github.com/rappen/CustomActionTester/issues/32

**Comment by drivardxrm** [comment]
Awesome, 
I will try to fix a couple of other things and I should make an official release very soon.
