### ISSUE TITLE
Further improve compatibility with OnPremises: entitylogicalname/logicalentityname

### ISSUE THREAD

**Issue by janis-veinbergs** [drivardxrm/XTB.CustomApiManager#21]
Thank you for #17

I found another difference between online/on-premises. The `logicalentityname` for `customapirequestparameter` and `customapiresponseproperty` is named... _drumroll,,,_ `entitylogicalname`

![image](https://github.com/drivardxrm/XTB.CustomApiManager/assets/714667/34c954fa-5045-4306-9f88-79177ff0358a)

PR is incoming.

**Comment by drivardxrm** [comment]
Hi @janis-veinbergs,
Good catch, I'll try to integrate the PR soon and push a new version.

Thanks
