### ISSUE TITLE
Issue with Binding custom API 

### ISSUE THREAD

**Issue by JoePittsy** [drivardxrm/XTB.CustomApiManager#23]
When creating a new API, If you bind to an entity then select your plugin and save the bound entity will be aaduser regardless of your selection in the UI. 

It works as expected if you select your plugin and then bind. 

---
- Deployment: Online
- DB Version: 9.2.23104.216
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.10.67
- Tool Version: 1.2023.10.218

**Comment by drivardxrm** [comment]
Hi @JoePittsy,

I tried several times and unfortunately I can't reproduce the issue you are describing.
I have the same version of the CustomApi manager and XrmToolbox.

Maybe I'm not doing the exact same steps. I f you could send me a quick video or animated gif, I would be curious to see this,

Thanks for the feedback.

**Comment by JoePittsy** [comment]
Hi @drivardxrm 

Annoyingly I can't reproduce it either now! 

Regardless thank you for developing the tool, it is super helpful : )
