### ISSUE TITLE
Tabbing is not in proper order

### ISSUE THREAD

**Issue by Power-Maverick** [drivardxrm/XTB.CustomApiManager#9]
I normally use the keyboard to tab through controls and most of the controls are not in order and had to use a mouse pointer to go to the next field on the form.

---
- Deployment: Online
- DB Version: 9.2.21093.152
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.9.52
- Tool Version: 1.2021.7.54

**Comment by drivardxrm** [comment]
Included in v1.2021.11.59
